name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Send email notification
      run: |
        sudo apt-get install git-email
        git config --global --edit
        git send-email --to=ivancicva@gmail.com --smtp-server=smtp.googlemail.com --smtp-encryption=tls --smtp-server-port=587 --smtp-user=youremail@gmail.com --no-chain-reply-to <<< "Your build completed."

